#!/bin/bash
mkdir -p ../build/dist
cd ../build
cmake -DCMAKE_TOOLCHAIN_FILE=$EMSDK/upstream/emscripten/cmake/Modules/Platform/Emscripten.cmake -DCMAKE_BUILD_TYPE=Release -G "Unix Makefiles"  ..
make -j$((`nproc`-1)) install
